//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace MvcDTS.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TSEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TSEntities object using the connection string found in the 'TSEntities' section of the application configuration file.
        /// </summary>
        public TSEntities() : base("name=TSEntities", "TSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TSEntities object.
        /// </summary>
        public TSEntities(string connectionString) : base(connectionString, "TSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TSEntities object.
        /// </summary>
        public TSEntities(EntityConnection connection) : base(connection, "TSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EMPLOYEE> EMPLOYEEs
        {
            get
            {
                if ((_EMPLOYEEs == null))
                {
                    _EMPLOYEEs = base.CreateObjectSet<EMPLOYEE>("EMPLOYEEs");
                }
                return _EMPLOYEEs;
            }
        }
        private ObjectSet<EMPLOYEE> _EMPLOYEEs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PART_NUM_MAP> PART_NUM_MAP
        {
            get
            {
                if ((_PART_NUM_MAP == null))
                {
                    _PART_NUM_MAP = base.CreateObjectSet<PART_NUM_MAP>("PART_NUM_MAP");
                }
                return _PART_NUM_MAP;
            }
        }
        private ObjectSet<PART_NUM_MAP> _PART_NUM_MAP;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WIP_CODE_MAP_org> WIP_CODE_MAP_org
        {
            get
            {
                if ((_WIP_CODE_MAP_org == null))
                {
                    _WIP_CODE_MAP_org = base.CreateObjectSet<WIP_CODE_MAP_org>("WIP_CODE_MAP_org");
                }
                return _WIP_CODE_MAP_org;
            }
        }
        private ObjectSet<WIP_CODE_MAP_org> _WIP_CODE_MAP_org;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WIP_EVENT> WIP_EVENT
        {
            get
            {
                if ((_WIP_EVENT == null))
                {
                    _WIP_EVENT = base.CreateObjectSet<WIP_EVENT>("WIP_EVENT");
                }
                return _WIP_EVENT;
            }
        }
        private ObjectSet<WIP_EVENT> _WIP_EVENT;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WIP_STATE> WIP_STATE
        {
            get
            {
                if ((_WIP_STATE == null))
                {
                    _WIP_STATE = base.CreateObjectSet<WIP_STATE>("WIP_STATE");
                }
                return _WIP_STATE;
            }
        }
        private ObjectSet<WIP_STATE> _WIP_STATE;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vw_dtscodemap> vw_dtscodemap
        {
            get
            {
                if ((_vw_dtscodemap == null))
                {
                    _vw_dtscodemap = base.CreateObjectSet<vw_dtscodemap>("vw_dtscodemap");
                }
                return _vw_dtscodemap;
            }
        }
        private ObjectSet<vw_dtscodemap> _vw_dtscodemap;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EMPLOYEEs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEMPLOYEEs(EMPLOYEE eMPLOYEE)
        {
            base.AddObject("EMPLOYEEs", eMPLOYEE);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PART_NUM_MAP EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPART_NUM_MAP(PART_NUM_MAP pART_NUM_MAP)
        {
            base.AddObject("PART_NUM_MAP", pART_NUM_MAP);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WIP_CODE_MAP_org EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWIP_CODE_MAP_org(WIP_CODE_MAP_org wIP_CODE_MAP_org)
        {
            base.AddObject("WIP_CODE_MAP_org", wIP_CODE_MAP_org);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WIP_EVENT EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWIP_EVENT(WIP_EVENT wIP_EVENT)
        {
            base.AddObject("WIP_EVENT", wIP_EVENT);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WIP_STATE EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWIP_STATE(WIP_STATE wIP_STATE)
        {
            base.AddObject("WIP_STATE", wIP_STATE);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vw_dtscodemap EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovw_dtscodemap(vw_dtscodemap vw_dtscodemap)
        {
            base.AddObject("vw_dtscodemap", vw_dtscodemap);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TSModel", Name="EMPLOYEE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EMPLOYEE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EMPLOYEE object.
        /// </summary>
        /// <param name="gLOBAL_ID">Initial value of the GLOBAL_ID property.</param>
        /// <param name="fIRST_NAME">Initial value of the FIRST_NAME property.</param>
        /// <param name="lAST_NAME">Initial value of the LAST_NAME property.</param>
        /// <param name="eMAIL">Initial value of the EMAIL property.</param>
        public static EMPLOYEE CreateEMPLOYEE(global::System.String gLOBAL_ID, global::System.String fIRST_NAME, global::System.String lAST_NAME, global::System.String eMAIL)
        {
            EMPLOYEE eMPLOYEE = new EMPLOYEE();
            eMPLOYEE.GLOBAL_ID = gLOBAL_ID;
            eMPLOYEE.FIRST_NAME = fIRST_NAME;
            eMPLOYEE.LAST_NAME = lAST_NAME;
            eMPLOYEE.EMAIL = eMAIL;
            return eMPLOYEE;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GLOBAL_ID
        {
            get
            {
                return _GLOBAL_ID;
            }
            set
            {
                if (_GLOBAL_ID != value)
                {
                    OnGLOBAL_IDChanging(value);
                    ReportPropertyChanging("GLOBAL_ID");
                    _GLOBAL_ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("GLOBAL_ID");
                    OnGLOBAL_IDChanged();
                }
            }
        }
        private global::System.String _GLOBAL_ID;
        partial void OnGLOBAL_IDChanging(global::System.String value);
        partial void OnGLOBAL_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FIRST_NAME
        {
            get
            {
                return _FIRST_NAME;
            }
            set
            {
                OnFIRST_NAMEChanging(value);
                ReportPropertyChanging("FIRST_NAME");
                _FIRST_NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FIRST_NAME");
                OnFIRST_NAMEChanged();
            }
        }
        private global::System.String _FIRST_NAME;
        partial void OnFIRST_NAMEChanging(global::System.String value);
        partial void OnFIRST_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LAST_NAME
        {
            get
            {
                return _LAST_NAME;
            }
            set
            {
                OnLAST_NAMEChanging(value);
                ReportPropertyChanging("LAST_NAME");
                _LAST_NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LAST_NAME");
                OnLAST_NAMEChanged();
            }
        }
        private global::System.String _LAST_NAME;
        partial void OnLAST_NAMEChanging(global::System.String value);
        partial void OnLAST_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EMAIL
        {
            get
            {
                return _EMAIL;
            }
            set
            {
                OnEMAILChanging(value);
                ReportPropertyChanging("EMAIL");
                _EMAIL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EMAIL");
                OnEMAILChanged();
            }
        }
        private global::System.String _EMAIL;
        partial void OnEMAILChanging(global::System.String value);
        partial void OnEMAILChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SUB_INV_CODE
        {
            get
            {
                return _SUB_INV_CODE;
            }
            set
            {
                OnSUB_INV_CODEChanging(value);
                ReportPropertyChanging("SUB_INV_CODE");
                _SUB_INV_CODE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SUB_INV_CODE");
                OnSUB_INV_CODEChanged();
            }
        }
        private global::System.String _SUB_INV_CODE;
        partial void OnSUB_INV_CODEChanging(global::System.String value);
        partial void OnSUB_INV_CODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AREA_CODE
        {
            get
            {
                return _AREA_CODE;
            }
            set
            {
                OnAREA_CODEChanging(value);
                ReportPropertyChanging("AREA_CODE");
                _AREA_CODE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AREA_CODE");
                OnAREA_CODEChanged();
            }
        }
        private global::System.String _AREA_CODE;
        partial void OnAREA_CODEChanging(global::System.String value);
        partial void OnAREA_CODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MANAGER_GID
        {
            get
            {
                return _MANAGER_GID;
            }
            set
            {
                OnMANAGER_GIDChanging(value);
                ReportPropertyChanging("MANAGER_GID");
                _MANAGER_GID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MANAGER_GID");
                OnMANAGER_GIDChanged();
            }
        }
        private global::System.String _MANAGER_GID;
        partial void OnMANAGER_GIDChanging(global::System.String value);
        partial void OnMANAGER_GIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TSModel", Name="PART_NUM_MAP")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PART_NUM_MAP : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PART_NUM_MAP object.
        /// </summary>
        /// <param name="pART_NUM">Initial value of the PART_NUM property.</param>
        public static PART_NUM_MAP CreatePART_NUM_MAP(global::System.String pART_NUM)
        {
            PART_NUM_MAP pART_NUM_MAP = new PART_NUM_MAP();
            pART_NUM_MAP.PART_NUM = pART_NUM;
            return pART_NUM_MAP;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PART_NUM
        {
            get
            {
                return _PART_NUM;
            }
            set
            {
                if (_PART_NUM != value)
                {
                    OnPART_NUMChanging(value);
                    ReportPropertyChanging("PART_NUM");
                    _PART_NUM = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PART_NUM");
                    OnPART_NUMChanged();
                }
            }
        }
        private global::System.String _PART_NUM;
        partial void OnPART_NUMChanging(global::System.String value);
        partial void OnPART_NUMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TYPE
        {
            get
            {
                return _TYPE;
            }
            set
            {
                OnTYPEChanging(value);
                ReportPropertyChanging("TYPE");
                _TYPE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TYPE");
                OnTYPEChanged();
            }
        }
        private global::System.String _TYPE;
        partial void OnTYPEChanging(global::System.String value);
        partial void OnTYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FAMILY
        {
            get
            {
                return _FAMILY;
            }
            set
            {
                OnFAMILYChanging(value);
                ReportPropertyChanging("FAMILY");
                _FAMILY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FAMILY");
                OnFAMILYChanged();
            }
        }
        private global::System.String _FAMILY;
        partial void OnFAMILYChanging(global::System.String value);
        partial void OnFAMILYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MODEL_NUM
        {
            get
            {
                return _MODEL_NUM;
            }
            set
            {
                OnMODEL_NUMChanging(value);
                ReportPropertyChanging("MODEL_NUM");
                _MODEL_NUM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MODEL_NUM");
                OnMODEL_NUMChanged();
            }
        }
        private global::System.String _MODEL_NUM;
        partial void OnMODEL_NUMChanging(global::System.String value);
        partial void OnMODEL_NUMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CUSTOMER
        {
            get
            {
                return _CUSTOMER;
            }
            set
            {
                OnCUSTOMERChanging(value);
                ReportPropertyChanging("CUSTOMER");
                _CUSTOMER = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CUSTOMER");
                OnCUSTOMERChanged();
            }
        }
        private global::System.String _CUSTOMER;
        partial void OnCUSTOMERChanging(global::System.String value);
        partial void OnCUSTOMERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CUST_PART_NUM
        {
            get
            {
                return _CUST_PART_NUM;
            }
            set
            {
                OnCUST_PART_NUMChanging(value);
                ReportPropertyChanging("CUST_PART_NUM");
                _CUST_PART_NUM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CUST_PART_NUM");
                OnCUST_PART_NUMChanged();
            }
        }
        private global::System.String _CUST_PART_NUM;
        partial void OnCUST_PART_NUMChanging(global::System.String value);
        partial void OnCUST_PART_NUMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SITE
        {
            get
            {
                return _SITE;
            }
            set
            {
                OnSITEChanging(value);
                ReportPropertyChanging("SITE");
                _SITE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SITE");
                OnSITEChanged();
            }
        }
        private global::System.String _SITE;
        partial void OnSITEChanging(global::System.String value);
        partial void OnSITEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ACTIVE
        {
            get
            {
                return _ACTIVE;
            }
            set
            {
                OnACTIVEChanging(value);
                ReportPropertyChanging("ACTIVE");
                _ACTIVE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ACTIVE");
                OnACTIVEChanged();
            }
        }
        private Nullable<global::System.Decimal> _ACTIVE;
        partial void OnACTIVEChanging(Nullable<global::System.Decimal> value);
        partial void OnACTIVEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> NUM_ZONE
        {
            get
            {
                return _NUM_ZONE;
            }
            set
            {
                OnNUM_ZONEChanging(value);
                ReportPropertyChanging("NUM_ZONE");
                _NUM_ZONE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NUM_ZONE");
                OnNUM_ZONEChanged();
            }
        }
        private Nullable<global::System.Decimal> _NUM_ZONE;
        partial void OnNUM_ZONEChanging(Nullable<global::System.Decimal> value);
        partial void OnNUM_ZONEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> NUM_HEADS
        {
            get
            {
                return _NUM_HEADS;
            }
            set
            {
                OnNUM_HEADSChanging(value);
                ReportPropertyChanging("NUM_HEADS");
                _NUM_HEADS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NUM_HEADS");
                OnNUM_HEADSChanged();
            }
        }
        private Nullable<global::System.Decimal> _NUM_HEADS;
        partial void OnNUM_HEADSChanging(Nullable<global::System.Decimal> value);
        partial void OnNUM_HEADSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String INTERFACE
        {
            get
            {
                return _INTERFACE;
            }
            set
            {
                OnINTERFACEChanging(value);
                ReportPropertyChanging("INTERFACE");
                _INTERFACE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("INTERFACE");
                OnINTERFACEChanged();
            }
        }
        private global::System.String _INTERFACE;
        partial void OnINTERFACEChanging(global::System.String value);
        partial void OnINTERFACEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DESCRIP
        {
            get
            {
                return _DESCRIP;
            }
            set
            {
                OnDESCRIPChanging(value);
                ReportPropertyChanging("DESCRIP");
                _DESCRIP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DESCRIP");
                OnDESCRIPChanged();
            }
        }
        private global::System.String _DESCRIP;
        partial void OnDESCRIPChanging(global::System.String value);
        partial void OnDESCRIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PART_NUM_GROUP
        {
            get
            {
                return _PART_NUM_GROUP;
            }
            set
            {
                OnPART_NUM_GROUPChanging(value);
                ReportPropertyChanging("PART_NUM_GROUP");
                _PART_NUM_GROUP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PART_NUM_GROUP");
                OnPART_NUM_GROUPChanged();
            }
        }
        private global::System.String _PART_NUM_GROUP;
        partial void OnPART_NUM_GROUPChanging(global::System.String value);
        partial void OnPART_NUM_GROUPChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TSModel", Name="vw_dtscodemap")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vw_dtscodemap : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vw_dtscodemap object.
        /// </summary>
        /// <param name="sUB_INV_CODE">Initial value of the SUB_INV_CODE property.</param>
        /// <param name="aREA_CODE">Initial value of the AREA_CODE property.</param>
        public static vw_dtscodemap Createvw_dtscodemap(global::System.String sUB_INV_CODE, global::System.String aREA_CODE)
        {
            vw_dtscodemap vw_dtscodemap = new vw_dtscodemap();
            vw_dtscodemap.SUB_INV_CODE = sUB_INV_CODE;
            vw_dtscodemap.AREA_CODE = aREA_CODE;
            return vw_dtscodemap;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SUB_INV_CODE
        {
            get
            {
                return _SUB_INV_CODE;
            }
            set
            {
                if (_SUB_INV_CODE != value)
                {
                    OnSUB_INV_CODEChanging(value);
                    ReportPropertyChanging("SUB_INV_CODE");
                    _SUB_INV_CODE = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SUB_INV_CODE");
                    OnSUB_INV_CODEChanged();
                }
            }
        }
        private global::System.String _SUB_INV_CODE;
        partial void OnSUB_INV_CODEChanging(global::System.String value);
        partial void OnSUB_INV_CODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AREA_CODE
        {
            get
            {
                return _AREA_CODE;
            }
            set
            {
                if (_AREA_CODE != value)
                {
                    OnAREA_CODEChanging(value);
                    ReportPropertyChanging("AREA_CODE");
                    _AREA_CODE = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("AREA_CODE");
                    OnAREA_CODEChanged();
                }
            }
        }
        private global::System.String _AREA_CODE;
        partial void OnAREA_CODEChanging(global::System.String value);
        partial void OnAREA_CODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DESCRIP
        {
            get
            {
                return _DESCRIP;
            }
            set
            {
                OnDESCRIPChanging(value);
                ReportPropertyChanging("DESCRIP");
                _DESCRIP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DESCRIP");
                OnDESCRIPChanged();
            }
        }
        private global::System.String _DESCRIP;
        partial void OnDESCRIPChanging(global::System.String value);
        partial void OnDESCRIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OWNER_EMP_NUM
        {
            get
            {
                return _OWNER_EMP_NUM;
            }
            set
            {
                OnOWNER_EMP_NUMChanging(value);
                ReportPropertyChanging("OWNER_EMP_NUM");
                _OWNER_EMP_NUM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OWNER_EMP_NUM");
                OnOWNER_EMP_NUMChanged();
            }
        }
        private global::System.String _OWNER_EMP_NUM;
        partial void OnOWNER_EMP_NUMChanging(global::System.String value);
        partial void OnOWNER_EMP_NUMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SUB_TOTAL
        {
            get
            {
                return _SUB_TOTAL;
            }
            set
            {
                OnSUB_TOTALChanging(value);
                ReportPropertyChanging("SUB_TOTAL");
                _SUB_TOTAL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SUB_TOTAL");
                OnSUB_TOTALChanged();
            }
        }
        private Nullable<global::System.Int32> _SUB_TOTAL;
        partial void OnSUB_TOTALChanging(Nullable<global::System.Int32> value);
        partial void OnSUB_TOTALChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TSModel", Name="WIP_CODE_MAP_org")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WIP_CODE_MAP_org : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WIP_CODE_MAP_org object.
        /// </summary>
        /// <param name="sITE">Initial value of the SITE property.</param>
        /// <param name="sUB_INV_CODE">Initial value of the SUB_INV_CODE property.</param>
        /// <param name="aREA_CODE">Initial value of the AREA_CODE property.</param>
        public static WIP_CODE_MAP_org CreateWIP_CODE_MAP_org(global::System.String sITE, global::System.String sUB_INV_CODE, global::System.String aREA_CODE)
        {
            WIP_CODE_MAP_org wIP_CODE_MAP_org = new WIP_CODE_MAP_org();
            wIP_CODE_MAP_org.SITE = sITE;
            wIP_CODE_MAP_org.SUB_INV_CODE = sUB_INV_CODE;
            wIP_CODE_MAP_org.AREA_CODE = aREA_CODE;
            return wIP_CODE_MAP_org;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SITE
        {
            get
            {
                return _SITE;
            }
            set
            {
                if (_SITE != value)
                {
                    OnSITEChanging(value);
                    ReportPropertyChanging("SITE");
                    _SITE = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SITE");
                    OnSITEChanged();
                }
            }
        }
        private global::System.String _SITE;
        partial void OnSITEChanging(global::System.String value);
        partial void OnSITEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SUB_INV_CODE
        {
            get
            {
                return _SUB_INV_CODE;
            }
            set
            {
                if (_SUB_INV_CODE != value)
                {
                    OnSUB_INV_CODEChanging(value);
                    ReportPropertyChanging("SUB_INV_CODE");
                    _SUB_INV_CODE = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SUB_INV_CODE");
                    OnSUB_INV_CODEChanged();
                }
            }
        }
        private global::System.String _SUB_INV_CODE;
        partial void OnSUB_INV_CODEChanging(global::System.String value);
        partial void OnSUB_INV_CODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AREA_CODE
        {
            get
            {
                return _AREA_CODE;
            }
            set
            {
                if (_AREA_CODE != value)
                {
                    OnAREA_CODEChanging(value);
                    ReportPropertyChanging("AREA_CODE");
                    _AREA_CODE = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("AREA_CODE");
                    OnAREA_CODEChanged();
                }
            }
        }
        private global::System.String _AREA_CODE;
        partial void OnAREA_CODEChanging(global::System.String value);
        partial void OnAREA_CODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COST_CENTER
        {
            get
            {
                return _COST_CENTER;
            }
            set
            {
                OnCOST_CENTERChanging(value);
                ReportPropertyChanging("COST_CENTER");
                _COST_CENTER = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COST_CENTER");
                OnCOST_CENTERChanged();
            }
        }
        private global::System.String _COST_CENTER;
        partial void OnCOST_CENTERChanging(global::System.String value);
        partial void OnCOST_CENTERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DESCRIP
        {
            get
            {
                return _DESCRIP;
            }
            set
            {
                OnDESCRIPChanging(value);
                ReportPropertyChanging("DESCRIP");
                _DESCRIP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DESCRIP");
                OnDESCRIPChanged();
            }
        }
        private global::System.String _DESCRIP;
        partial void OnDESCRIPChanging(global::System.String value);
        partial void OnDESCRIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OWNER_EMP_NUM
        {
            get
            {
                return _OWNER_EMP_NUM;
            }
            set
            {
                OnOWNER_EMP_NUMChanging(value);
                ReportPropertyChanging("OWNER_EMP_NUM");
                _OWNER_EMP_NUM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OWNER_EMP_NUM");
                OnOWNER_EMP_NUMChanged();
            }
        }
        private global::System.String _OWNER_EMP_NUM;
        partial void OnOWNER_EMP_NUMChanging(global::System.String value);
        partial void OnOWNER_EMP_NUMChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TSModel", Name="WIP_EVENT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WIP_EVENT : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WIP_EVENT object.
        /// </summary>
        /// <param name="sERIAL_NUM">Initial value of the SERIAL_NUM property.</param>
        /// <param name="tRANS_SEQ">Initial value of the TRANS_SEQ property.</param>
        /// <param name="eVENT_DATE">Initial value of the EVENT_DATE property.</param>
        public static WIP_EVENT CreateWIP_EVENT(global::System.String sERIAL_NUM, global::System.Decimal tRANS_SEQ, global::System.DateTime eVENT_DATE)
        {
            WIP_EVENT wIP_EVENT = new WIP_EVENT();
            wIP_EVENT.SERIAL_NUM = sERIAL_NUM;
            wIP_EVENT.TRANS_SEQ = tRANS_SEQ;
            wIP_EVENT.EVENT_DATE = eVENT_DATE;
            return wIP_EVENT;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SERIAL_NUM
        {
            get
            {
                return _SERIAL_NUM;
            }
            set
            {
                if (_SERIAL_NUM != value)
                {
                    OnSERIAL_NUMChanging(value);
                    ReportPropertyChanging("SERIAL_NUM");
                    _SERIAL_NUM = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SERIAL_NUM");
                    OnSERIAL_NUMChanged();
                }
            }
        }
        private global::System.String _SERIAL_NUM;
        partial void OnSERIAL_NUMChanging(global::System.String value);
        partial void OnSERIAL_NUMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TRANS_SEQ
        {
            get
            {
                return _TRANS_SEQ;
            }
            set
            {
                if (_TRANS_SEQ != value)
                {
                    OnTRANS_SEQChanging(value);
                    ReportPropertyChanging("TRANS_SEQ");
                    _TRANS_SEQ = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TRANS_SEQ");
                    OnTRANS_SEQChanged();
                }
            }
        }
        private global::System.Decimal _TRANS_SEQ;
        partial void OnTRANS_SEQChanging(global::System.Decimal value);
        partial void OnTRANS_SEQChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EVENT_DATE
        {
            get
            {
                return _EVENT_DATE;
            }
            set
            {
                if (_EVENT_DATE != value)
                {
                    OnEVENT_DATEChanging(value);
                    ReportPropertyChanging("EVENT_DATE");
                    _EVENT_DATE = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EVENT_DATE");
                    OnEVENT_DATEChanged();
                }
            }
        }
        private global::System.DateTime _EVENT_DATE;
        partial void OnEVENT_DATEChanging(global::System.DateTime value);
        partial void OnEVENT_DATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PART_NUM
        {
            get
            {
                return _PART_NUM;
            }
            set
            {
                OnPART_NUMChanging(value);
                ReportPropertyChanging("PART_NUM");
                _PART_NUM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PART_NUM");
                OnPART_NUMChanged();
            }
        }
        private global::System.String _PART_NUM;
        partial void OnPART_NUMChanging(global::System.String value);
        partial void OnPART_NUMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HDA_PART_NUM
        {
            get
            {
                return _HDA_PART_NUM;
            }
            set
            {
                OnHDA_PART_NUMChanging(value);
                ReportPropertyChanging("HDA_PART_NUM");
                _HDA_PART_NUM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HDA_PART_NUM");
                OnHDA_PART_NUMChanged();
            }
        }
        private global::System.String _HDA_PART_NUM;
        partial void OnHDA_PART_NUMChanging(global::System.String value);
        partial void OnHDA_PART_NUMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PCBA_PART_NUM
        {
            get
            {
                return _PCBA_PART_NUM;
            }
            set
            {
                OnPCBA_PART_NUMChanging(value);
                ReportPropertyChanging("PCBA_PART_NUM");
                _PCBA_PART_NUM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PCBA_PART_NUM");
                OnPCBA_PART_NUMChanged();
            }
        }
        private global::System.String _PCBA_PART_NUM;
        partial void OnPCBA_PART_NUMChanging(global::System.String value);
        partial void OnPCBA_PART_NUMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BUILD_GROUP
        {
            get
            {
                return _BUILD_GROUP;
            }
            set
            {
                OnBUILD_GROUPChanging(value);
                ReportPropertyChanging("BUILD_GROUP");
                _BUILD_GROUP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BUILD_GROUP");
                OnBUILD_GROUPChanged();
            }
        }
        private global::System.String _BUILD_GROUP;
        partial void OnBUILD_GROUPChanging(global::System.String value);
        partial void OnBUILD_GROUPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SUB_BUILD_GROUP
        {
            get
            {
                return _SUB_BUILD_GROUP;
            }
            set
            {
                OnSUB_BUILD_GROUPChanging(value);
                ReportPropertyChanging("SUB_BUILD_GROUP");
                _SUB_BUILD_GROUP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SUB_BUILD_GROUP");
                OnSUB_BUILD_GROUPChanged();
            }
        }
        private global::System.String _SUB_BUILD_GROUP;
        partial void OnSUB_BUILD_GROUPChanging(global::System.String value);
        partial void OnSUB_BUILD_GROUPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OPERATION
        {
            get
            {
                return _OPERATION;
            }
            set
            {
                OnOPERATIONChanging(value);
                ReportPropertyChanging("OPERATION");
                _OPERATION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OPERATION");
                OnOPERATIONChanged();
            }
        }
        private global::System.String _OPERATION;
        partial void OnOPERATIONChanging(global::System.String value);
        partial void OnOPERATIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EQUIP_ID
        {
            get
            {
                return _EQUIP_ID;
            }
            set
            {
                OnEQUIP_IDChanging(value);
                ReportPropertyChanging("EQUIP_ID");
                _EQUIP_ID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EQUIP_ID");
                OnEQUIP_IDChanged();
            }
        }
        private global::System.String _EQUIP_ID;
        partial void OnEQUIP_IDChanging(global::System.String value);
        partial void OnEQUIP_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SLOT
        {
            get
            {
                return _SLOT;
            }
            set
            {
                OnSLOTChanging(value);
                ReportPropertyChanging("SLOT");
                _SLOT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SLOT");
                OnSLOTChanged();
            }
        }
        private global::System.String _SLOT;
        partial void OnSLOTChanging(global::System.String value);
        partial void OnSLOTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EMP_NUM
        {
            get
            {
                return _EMP_NUM;
            }
            set
            {
                OnEMP_NUMChanging(value);
                ReportPropertyChanging("EMP_NUM");
                _EMP_NUM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EMP_NUM");
                OnEMP_NUMChanged();
            }
        }
        private global::System.String _EMP_NUM;
        partial void OnEMP_NUMChanging(global::System.String value);
        partial void OnEMP_NUMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SUB_INV_CODE
        {
            get
            {
                return _SUB_INV_CODE;
            }
            set
            {
                OnSUB_INV_CODEChanging(value);
                ReportPropertyChanging("SUB_INV_CODE");
                _SUB_INV_CODE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SUB_INV_CODE");
                OnSUB_INV_CODEChanged();
            }
        }
        private global::System.String _SUB_INV_CODE;
        partial void OnSUB_INV_CODEChanging(global::System.String value);
        partial void OnSUB_INV_CODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AREA_CODE
        {
            get
            {
                return _AREA_CODE;
            }
            set
            {
                OnAREA_CODEChanging(value);
                ReportPropertyChanging("AREA_CODE");
                _AREA_CODE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AREA_CODE");
                OnAREA_CODEChanged();
            }
        }
        private global::System.String _AREA_CODE;
        partial void OnAREA_CODEChanging(global::System.String value);
        partial void OnAREA_CODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EVENT_STATUS
        {
            get
            {
                return _EVENT_STATUS;
            }
            set
            {
                OnEVENT_STATUSChanging(value);
                ReportPropertyChanging("EVENT_STATUS");
                _EVENT_STATUS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EVENT_STATUS");
                OnEVENT_STATUSChanged();
            }
        }
        private global::System.String _EVENT_STATUS;
        partial void OnEVENT_STATUSChanging(global::System.String value);
        partial void OnEVENT_STATUSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PRIME
        {
            get
            {
                return _PRIME;
            }
            set
            {
                OnPRIMEChanging(value);
                ReportPropertyChanging("PRIME");
                _PRIME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PRIME");
                OnPRIMEChanged();
            }
        }
        private global::System.String _PRIME;
        partial void OnPRIMEChanging(global::System.String value);
        partial void OnPRIMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PREV_SUB_INV_CODE
        {
            get
            {
                return _PREV_SUB_INV_CODE;
            }
            set
            {
                OnPREV_SUB_INV_CODEChanging(value);
                ReportPropertyChanging("PREV_SUB_INV_CODE");
                _PREV_SUB_INV_CODE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PREV_SUB_INV_CODE");
                OnPREV_SUB_INV_CODEChanged();
            }
        }
        private global::System.String _PREV_SUB_INV_CODE;
        partial void OnPREV_SUB_INV_CODEChanging(global::System.String value);
        partial void OnPREV_SUB_INV_CODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PREV_AREA_CODE
        {
            get
            {
                return _PREV_AREA_CODE;
            }
            set
            {
                OnPREV_AREA_CODEChanging(value);
                ReportPropertyChanging("PREV_AREA_CODE");
                _PREV_AREA_CODE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PREV_AREA_CODE");
                OnPREV_AREA_CODEChanged();
            }
        }
        private global::System.String _PREV_AREA_CODE;
        partial void OnPREV_AREA_CODEChanging(global::System.String value);
        partial void OnPREV_AREA_CODEChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TSModel", Name="WIP_STATE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WIP_STATE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WIP_STATE object.
        /// </summary>
        /// <param name="sERIAL_NUM">Initial value of the SERIAL_NUM property.</param>
        public static WIP_STATE CreateWIP_STATE(global::System.String sERIAL_NUM)
        {
            WIP_STATE wIP_STATE = new WIP_STATE();
            wIP_STATE.SERIAL_NUM = sERIAL_NUM;
            return wIP_STATE;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SERIAL_NUM
        {
            get
            {
                return _SERIAL_NUM;
            }
            set
            {
                if (_SERIAL_NUM != value)
                {
                    OnSERIAL_NUMChanging(value);
                    ReportPropertyChanging("SERIAL_NUM");
                    _SERIAL_NUM = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SERIAL_NUM");
                    OnSERIAL_NUMChanged();
                }
            }
        }
        private global::System.String _SERIAL_NUM;
        partial void OnSERIAL_NUMChanging(global::System.String value);
        partial void OnSERIAL_NUMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OPERATION
        {
            get
            {
                return _OPERATION;
            }
            set
            {
                OnOPERATIONChanging(value);
                ReportPropertyChanging("OPERATION");
                _OPERATION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OPERATION");
                OnOPERATIONChanged();
            }
        }
        private global::System.String _OPERATION;
        partial void OnOPERATIONChanging(global::System.String value);
        partial void OnOPERATIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String STATUS
        {
            get
            {
                return _STATUS;
            }
            set
            {
                OnSTATUSChanging(value);
                ReportPropertyChanging("STATUS");
                _STATUS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("STATUS");
                OnSTATUSChanged();
            }
        }
        private global::System.String _STATUS;
        partial void OnSTATUSChanging(global::System.String value);
        partial void OnSTATUSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PART_NUM
        {
            get
            {
                return _PART_NUM;
            }
            set
            {
                OnPART_NUMChanging(value);
                ReportPropertyChanging("PART_NUM");
                _PART_NUM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PART_NUM");
                OnPART_NUMChanged();
            }
        }
        private global::System.String _PART_NUM;
        partial void OnPART_NUMChanging(global::System.String value);
        partial void OnPART_NUMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BUILD_GROUP
        {
            get
            {
                return _BUILD_GROUP;
            }
            set
            {
                OnBUILD_GROUPChanging(value);
                ReportPropertyChanging("BUILD_GROUP");
                _BUILD_GROUP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BUILD_GROUP");
                OnBUILD_GROUPChanged();
            }
        }
        private global::System.String _BUILD_GROUP;
        partial void OnBUILD_GROUPChanging(global::System.String value);
        partial void OnBUILD_GROUPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SBG_FLAG
        {
            get
            {
                return _SBG_FLAG;
            }
            set
            {
                OnSBG_FLAGChanging(value);
                ReportPropertyChanging("SBG_FLAG");
                _SBG_FLAG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SBG_FLAG");
                OnSBG_FLAGChanged();
            }
        }
        private global::System.String _SBG_FLAG;
        partial void OnSBG_FLAGChanging(global::System.String value);
        partial void OnSBG_FLAGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HDA_PART_NUM
        {
            get
            {
                return _HDA_PART_NUM;
            }
            set
            {
                OnHDA_PART_NUMChanging(value);
                ReportPropertyChanging("HDA_PART_NUM");
                _HDA_PART_NUM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HDA_PART_NUM");
                OnHDA_PART_NUMChanged();
            }
        }
        private global::System.String _HDA_PART_NUM;
        partial void OnHDA_PART_NUMChanging(global::System.String value);
        partial void OnHDA_PART_NUMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PCBA_PART_NUM
        {
            get
            {
                return _PCBA_PART_NUM;
            }
            set
            {
                OnPCBA_PART_NUMChanging(value);
                ReportPropertyChanging("PCBA_PART_NUM");
                _PCBA_PART_NUM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PCBA_PART_NUM");
                OnPCBA_PART_NUMChanged();
            }
        }
        private global::System.String _PCBA_PART_NUM;
        partial void OnPCBA_PART_NUMChanging(global::System.String value);
        partial void OnPCBA_PART_NUMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PRIME
        {
            get
            {
                return _PRIME;
            }
            set
            {
                OnPRIMEChanging(value);
                ReportPropertyChanging("PRIME");
                _PRIME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PRIME");
                OnPRIMEChanged();
            }
        }
        private global::System.String _PRIME;
        partial void OnPRIMEChanging(global::System.String value);
        partial void OnPRIMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AREA_CODE
        {
            get
            {
                return _AREA_CODE;
            }
            set
            {
                OnAREA_CODEChanging(value);
                ReportPropertyChanging("AREA_CODE");
                _AREA_CODE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AREA_CODE");
                OnAREA_CODEChanged();
            }
        }
        private global::System.String _AREA_CODE;
        partial void OnAREA_CODEChanging(global::System.String value);
        partial void OnAREA_CODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SUB_INV_CODE
        {
            get
            {
                return _SUB_INV_CODE;
            }
            set
            {
                OnSUB_INV_CODEChanging(value);
                ReportPropertyChanging("SUB_INV_CODE");
                _SUB_INV_CODE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SUB_INV_CODE");
                OnSUB_INV_CODEChanged();
            }
        }
        private global::System.String _SUB_INV_CODE;
        partial void OnSUB_INV_CODEChanging(global::System.String value);
        partial void OnSUB_INV_CODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EQUIP_ID
        {
            get
            {
                return _EQUIP_ID;
            }
            set
            {
                OnEQUIP_IDChanging(value);
                ReportPropertyChanging("EQUIP_ID");
                _EQUIP_ID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EQUIP_ID");
                OnEQUIP_IDChanged();
            }
        }
        private global::System.String _EQUIP_ID;
        partial void OnEQUIP_IDChanging(global::System.String value);
        partial void OnEQUIP_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> SLOT
        {
            get
            {
                return _SLOT;
            }
            set
            {
                OnSLOTChanging(value);
                ReportPropertyChanging("SLOT");
                _SLOT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SLOT");
                OnSLOTChanged();
            }
        }
        private Nullable<global::System.Decimal> _SLOT;
        partial void OnSLOTChanging(Nullable<global::System.Decimal> value);
        partial void OnSLOTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PERIOD
        {
            get
            {
                return _PERIOD;
            }
            set
            {
                OnPERIODChanging(value);
                ReportPropertyChanging("PERIOD");
                _PERIOD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PERIOD");
                OnPERIODChanged();
            }
        }
        private Nullable<global::System.DateTime> _PERIOD;
        partial void OnPERIODChanging(Nullable<global::System.DateTime> value);
        partial void OnPERIODChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RWK_WIP_CODE
        {
            get
            {
                return _RWK_WIP_CODE;
            }
            set
            {
                OnRWK_WIP_CODEChanging(value);
                ReportPropertyChanging("RWK_WIP_CODE");
                _RWK_WIP_CODE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RWK_WIP_CODE");
                OnRWK_WIP_CODEChanged();
            }
        }
        private global::System.String _RWK_WIP_CODE;
        partial void OnRWK_WIP_CODEChanging(global::System.String value);
        partial void OnRWK_WIP_CODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RWK_CODE
        {
            get
            {
                return _RWK_CODE;
            }
            set
            {
                OnRWK_CODEChanging(value);
                ReportPropertyChanging("RWK_CODE");
                _RWK_CODE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RWK_CODE");
                OnRWK_CODEChanged();
            }
        }
        private global::System.String _RWK_CODE;
        partial void OnRWK_CODEChanging(global::System.String value);
        partial void OnRWK_CODEChanged();

        #endregion
    
    }

    #endregion
    
}
